name: Test

on:
    pull_request:
        branches:
            - main

env:
    GITHUB_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

jobs:
    test:
        if: startsWith(github.head_ref, 'release-please--')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install
            - run: pnpm proto:lint
